mybatis:
  type-aliases-package: com.study.springboard.models, com.study.springboard.dtos
  configuration:
    map-underscore-to-camel-case: true
    level:
      com.study.springboard.repository: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebrainsoft_study
    username: ebsoft
    password: ebsoft

    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 15MB

file:
  dir: C:\Users\82103\Desktop\upload\
