mybatis:
  type-aliases-package: com.study.springboard.models, com.study.springboard.dtos
  configuration:
    map-underscore-to-camel-case: true
    level:
      com.study.springboard.repository: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebrainsoft_study
    username: ebsoft
    password: ebsoft

